version: '2'
services:
  agencias-ud:
    container_name: agencias-ud
    build:
      context: agencias-ud
    image: agencias-ud:latest
    ports:
      - 18888:5000
    networks:
      - spring-cloud-network
  clientes-ud:
    container_name: clientes-ud
    build:
      context: clientes-ud
    image: clientes-ud:latest
    ports:
      - 19999:8000
    networks:
      - spring-cloud-network
networks:
      spring-cloud-network:
        driver: bridge